const { normalizeUrl } = require("../model");

function titleize(value) {
  return value
    .replace(/^www\./, "")
    .split(/[.-]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function extractUrl(inputUrl) {
  const sourceUrl = normalizeUrl(inputUrl);
  const url = new URL(sourceUrl);
  const vendor = titleize(url.hostname);
  const pathLabel = url.pathname.split("/").filter(Boolean).pop();
  const productName = pathLabel ? titleize(decodeURIComponent(pathLabel)) : `${vendor} source review`;
  const extractedAt = new Date().toISOString();

  return {
    adapter: "mock",
    sourceUrl,
    extractedAt,
    confidence: "weak",
    verificationStatus: "mock_unverified",
    blockers: ["Mock adapter only: page contents were not fetched."],
    evidence: [
      {
        field: "officialUrl",
        value: sourceUrl,
        sourceUrl,
        pageReference: url.pathname || "/",
        snippet: `Mock adapter recorded the submitted URL for later discovery: ${sourceUrl}`,
        confidence: "weak",
        verificationStatus: "mock_unverified",
      },
      {
        field: "candidateName",
        value: productName,
        sourceUrl,
        pageReference: url.pathname || "/",
        snippet: `Mock adapter derived a review-only label from the URL path: ${productName}`,
        confidence: "weak",
        verificationStatus: "mock_unverified",
      },
    ],
    sourcePatch: {
      sourceType: "unknown",
      officialUrl: sourceUrl,
      confidence: "weak",
      status: "needs_review",
      importantPages: [sourceUrl],
      extractableFields: ["officialUrl", "candidateName"],
      blockers: ["Mock adapter only: page contents were not fetched."],
      nextAction: "review mock evidence and replace with a real extraction adapter",
    },
    candidate: {
      vendor,
      productName,
      productUrl: sourceUrl,
      category: "Unknown",
      material: "Unknown",
      height: null,
      weight: null,
      price: null,
      imageRights: "unknown",
      bestFor: "Pending evidence review",
      notIdealFor: "Publication before verification",
      ownerAdvantage: "Pending evidence review",
      ownerRisk: "Mock record only; specs and media rights are unverified.",
      recommendationStatus: "needs_review",
      evidenceNotes: "Generated by the mock adapter from a submitted URL. Do not recommend or publish.",
      verificationStatus: "mock_unverified",
    },
  };
}

module.exports = { extractUrl };
